### Send POST request with Token

POST http://localhost:8080/join
Content-Type: application/json
Accept: application/json

{
  "email": "kj9772@naver.com"
}

### Send GET request with Token

GET http://localhost:8080/join/confirm?token=7b99e317-f512-43d8-bf78-156cb62673d6