### Send POST request with Token

POST http://localhost:8080/api/users/register
Content-Type: application/json
Accept: application/json

{
  "email": "kj9772@naver.com"
}

### Send GET request with Token

GET http://localhost:8080/api/users/register/confirm?token=@