spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://jaeyeop-blog-project.czeadcaqy0xy.ap-northeast-2.rds.amazonaws.com:3306/blog?serverTimezone=Asia/Seoul&useSSL=false
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: password

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        time_zone: Asia/Seoul
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    s3:
      bucket: jaeyeop-blog-project
      url: https://jaeyeop-blog-project.s3.ap-northeast-2.amazonaws.com/
    #      defaultImage: https://jaeyeop-blog-project.s3.ap-northeast-2.amazonaws.com/images/default.jpg
    region: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true


