cloud:
  aws:
    s3:
      bucket: jaeyeop-blog-project
      objectUrl: https://jaeyeop-blog-project.s3.ap-northeast-2.amazonaws.com/
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jaeyeop-blog-project.czeadcaqy0xy.ap-northeast-2.rds.amazonaws.com:3306/blog?serverTimezone=UTC&useSSL=false
    username: root
    password: password

  jpa:
    open-in-view: true # transaction!!
    hibernate:
      ddl-auto: update
      # naming: physical-strategy: org.hibernate.boot.model.naming.SpringPhysicalNamingStrategy -> underscore (default)
      # naming: physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl -> original naming
      # use-new-id-generator-mappings: false -> @GeneratedValue(strategy = GenerationType.IDENTITY)
    show-sql: false
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
